/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CoolToken } from "./CoolToken";
export type { IERC20 } from "./IERC20";

export { CoolToken__factory } from "./factories/CoolToken__factory";
export { IERC20__factory } from "./factories/IERC20__factory";
